name: C/C++ CI
on: [push, pull_request]

jobs:

  build-windows-msvc-qt6:
    name: Build Windows MSVC Qt 6
    runs-on: windows-latest
    steps:

      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: amd64
          toolset: 14.29

      #- name: Install boost
      #  uses: MarkusJx/install-boost@v2.0.0
      #  with:
      #    boost_version: 1.73.0

      - name: Install protobuf
        run: |
          vcpkg install protobuf
          dir C:\vcpkg\packages
          dir C:\vcpkg\packages\protobuf_x64-windows
          dir C:\vcpkg\packages\protobuf_x64-windows\lib
          dir C:\vcpkg\packages\protobuf_x64-windows\bin
          dir C:\vcpkg\packages\protobuf_x64-windows\tools\protobuf

      - name: Install Qt 6
        uses: jurplel/install-qt-action@v2.14.0
        with:
          version: 6.1.3
          modules: qtbase qttools

      - name: Download Boost
        uses: suisei-cn/actions-download-file@v1
        with:
          url: "Boost [this](https://boostorg.jfrog.io/artifactory/main/release/1.77.0/source/boost_1_77_0.zip)!"
          target: downloads/
          auto-match: true

      #- name: Download Protobuf
      #  uses: suisei-cn/actions-download-file@v1
      #  with:
      #    url: "Protobuf [this](https://github.com/protocolbuffers/protobuf/releases/download/v3.18.0-rc2/protobuf-cpp-3.18.0-rc-2.zip)!"
      #    target: downloads/
      #    auto-match: true

      - name: Download SQLite
        uses: suisei-cn/actions-download-file@v1
        with:
          url: "SQLite [this](https://www.sqlite.org/2021/sqlite-autoconf-3360000.tar.gz)!"
          target: downloads/
          auto-match: true

      - name: Download GStreamer
        uses: suisei-cn/actions-download-file@v1
        with:
          url: "GStreamer [this](https://gstreamer.freedesktop.org/data/pkg/windows/1.18.5/msvc/gstreamer-1.0-msvc-x86_64-1.18.5.msi)!"
          target: downloads/
          auto-match: true

      - name: Download GStreamer Devel
        uses: suisei-cn/actions-download-file@v1
        with:
          url: "GStreamer Devel [this](https://gstreamer.freedesktop.org/data/pkg/windows/1.18.5/msvc/gstreamer-1.0-devel-msvc-x86_64-1.18.5.msi)!"
          target: downloads/
          auto-match: true

      - name: Download GnuTLS
        uses: suisei-cn/actions-download-file@v1
        with:
          url: "GnutTLS [this](https://github.com/ShiftMediaProject/gnutls/releases/download/3.7.2/libgnutls_3.7.2_msvc14.zip)!"
          target: downloads/
          auto-match: true

      - name: Download TagLib
        uses: suisei-cn/actions-download-file@v1
        with:
          url: "TagLib [this](https://taglib.org/releases/taglib-1.12.tar.gz)!"
          target: downloads/
          auto-match: true

      - name: Extract Boost
        working-directory: D:\a\strawberry\strawberry
        run: 7z x d:\a\strawberry\strawberry\downloads\boost_1_77_0.zip

      - name: Debug
        run: |
          echo %PATH%
          cmake --version
          dir d:\a\strawberry\strawberry\boost_1_77_0

      #- name: Extract Protobuf
      #  working-directory: D:\a\strawberry\strawberry
      #  run: 7z x d:\a\strawberry\strawberry\downloads\protobuf-cpp-3.18.0-rc-2.zip

      - name: Extract SQLite
        working-directory: D:\a\strawberry\strawberry
        shell: bash
        run: tar -xvf /d/a/strawberry/strawberry/downloads/sqlite-autoconf-3360000.tar.gz

      - name: Grant Full Access to c:\windows\temp directory
        run: icacls "C:\Windows\Temp" /q /c /t /grant Users:F /T

      - name: Install GStreamer
        working-directory: D:\a\strawberry\strawberry\downloads
        run: msiexec /a D:\a\strawberry\strawberry\downloads\gstreamer-1.0-msvc-x86_64-1.18.5.msi /passive /qn

      - name: Wait for GStreamer installation to complete
        run: Start-Sleep -s 20
        shell: powershell

      - name: Install GStreamer Devel
        working-directory: D:\a\strawberry\strawberry\downloads
        run: msiexec /a D:\a\strawberry\strawberry\downloads\gstreamer-1.0-devel-msvc-x86_64-1.18.5.msi /passive /qn

      - name: Wait for GStreamer Devel installation to complete
        run: Start-Sleep -s 30
        shell: powershell

      - name: Extract GnuTLS
        working-directory: D:\a\strawberry\strawberry
        run: |
          mkdir gnutls
          cd gnutls
          7z x d:\a\strawberry\strawberry\downloads\libgnutls_3.7.2_msvc14.zip

      - name: Extract TagLib
        working-directory: D:\a\strawberry\strawberry
        shell: bash
        run: tar -xvf /d/a/strawberry/strawberry/downloads/taglib-1.12.tar.gz

      #- name: Show gstreamer install log
      #  working-directory: D:\a\strawberry\strawberry\downloads
      #  run: type gstreamer_install.log

      - name: Fix pkg files
        shell: bash
        run: |
          sed -i 's/c:\/projects\/repos\/cerbero.git\/1.18\/build\/dist/c:\/gstreamer\/1.0/g' /c/gstreamer/1.0/msvc_x86_64/lib/pkgconfig/*.pc
          cp C:/vcpkg/packages/protobuf_x86-windows/lib/pkgconfig/protobuf.pc /c/gstreamer/1.0/msvc_x86_64/lib/pkgconfig/

      #- name: Compile Protobuf
      #  env:
      #    CL: "/MP"
      #  working-directory: D:\a\strawberry\strawberry\protobuf-3.18.0-rc-2
      #  run: |
      #    cd cmake
      #    mkdir build
      #    cd build
      #    cmake .. -G "NMake Makefiles" -DCMAKE_BUILD_TYPE=Release -Dprotobuf_BUILD_SHARED_LIBS=ON -DCMAKE_INSTALL_PREFIX="d:/a/strawberry/strawberry/protobuf" -Dprotobuf_BUILD_TESTS=OFF
      #    nmake
      #    cmake --install .
      #    copy D:\a\strawberry\strawberry\protobuf-3.18.0-rc-2\cmake\build\protobuf.pc c:\gstreamer\1.0\msvc_x86_64\lib\pkgconfig\

      - name: Compile SQlite
        env:
          CL: "/MP"
        working-directory: D:\a\strawberry\strawberry\sqlite-autoconf-3360000
        run: nmake /f Makefile.msc

      - name: Compile TagLib
        env:
          CL: "/MP"
        working-directory: D:\a\strawberry\strawberry\taglib-1.12
        run: |
          mkdir build
          cd build
          cmake .. -G "NMake Makefiles" -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX="d:/a/strawberry/strawberry/taglib"
          nmake
          cmake --install .
          copy D:\a\strawberry\strawberry\taglib-1.12\build\taglib.pc c:\gstreamer\1.0\msvc_x86_64\lib\pkgconfig\

      #- name: Delete
      #  run: |
      #    del "C:/Program Files/CMake/share/cmake-3.21/Modules/FindBoost.cmake"
      #    del "C:/Program Files/CMake/share/cmake-3.21/Modules/FindProtobuf.cmake"

      - uses: actions/checkout@v1.2.0

      - name: Remove find_package(Protobuf)
        shell: bash
        run: |
          ls /d/a/strawberry/strawberry/
          sed -i 's/find_package(Boost.*//g' /d/a/strawberry/strawberry/CMakeLists.txt

      - name: Create Build Environment
        run: cmake -E make_directory build

      - name: Run CMake
        working-directory: build
        run: >
          cmake ..
          -DCMAKE_BUILD_TYPE=Release
          -DBUILD_WITH_QT6=ON
          -DBUILD_WERROR=OFF
          -DARCH=x86_64
          -DENABLE_WIN32_CONSOLE=OFF
          -DENABLE_DBUS=OFF
          -DENABLE_LIBGPOD=OFF
          -DENABLE_LIBMTP=OFF
          -DPKG_CONFIG_EXECUTABLE=C:/gstreamer/1.0/msvc_x86_64/bin/pkg-config.exe
          -DSQLITE_INCLUDE_DIRS=d:/a/strawberry/strawberry/sqlite-autoconf-3360000
          -DSQLITE_LIBRARY_DIRS=d:/a/strawberry/strawberry/sqlite-autoconf-3360000
          -DSQLITE_LIBRARIES=d:/a/strawberry/strawberry/sqlite-autoconf-3360000/sqlite3.lib
          -DGNUTLS_LIBRARY=d:/a/strawberry/strawberry/libgnutls_3.7.2_msvc14/lib/x64/gnutls.lib
          -DGNUTLS_INCLUDE_DIR=d:/a/strawberry/strawberry/libgnutls_3.7.2_msvc14/include
          -DGNUTLS_INCLUDE_DIRS=d:/a/strawberry/strawberry/libgnutls_3.7.2_msvc14/include
          -DBoost_DIR=d:/a/strawberry/strawberry/boost_1_77_0
          -DBoost_INCLUDE_DIR=d:/a/strawberry/strawberry/boost_1_77_0
          -DBoost_INCLUDE_DIRS=d:/a/strawberry/strawberry/boost_1_77_0
          -DProtobuf_LIBRARY=c:/vcpkg/packages/protobuf_x64-windows/lib/libprotobuf.lib
          -DProtobuf_INCLUDE_DIR=c:/vcpkg/packages/protobuf_x64-windows/include
          -DProtobuf_INCLUDE_DIRS=c:/vcpkg/packages/protobuf_x64-windows/include
          -DPROTOBUF_PROTOC_EXECUTABLE=c:/vcpkg/packages/protobuf_x64-windows/tools/protobuf/protoc.exe
          -DTAGLIB_INCLUDE_DIR=d:/a/strawberry/strawberry/taglib/include
          -DTAGLIB_INCLUDE_DIRS=d:/a/strawberry/strawberry/taglib/include

          #-DProtobuf_DIR=c:/vcpkg/packages/protobuf_x64-windows
          #-DProtobuf_LIBRARY_RELEASE=c:/vcpkg/packages/protobuf_x64-windows/lib/libprotobuf.lib

          #-DBoost_DIR=d:/a/strawberry/strawberry/boost/boost
          #-DBoost_INCLUDE_DIR=d:/a/strawberry/strawberry/boost/boost/include/boost-1_73
          #-DBoost_INCLUDE_DIRS=d:/a/strawberry/strawberry/boost/boost/include/boost-1_73

          #-DProtobuf_DIR=d:/a/strawberry/strawberry/protobuf
          #-DProtobuf_LIBRARY=d:/a/strawberry/strawberry/protobuf/lib/libprotobuf.lib
          #-DProtobuf_INCLUDE_DIR=d:/a/strawberry/strawberry/protobuf/include
          #-DProtobuf_INCLUDE_DIRS=d:/a/strawberry/strawberry/protobuf/include
          #-DProtobuf_PROTOC_EXECUTABLE=d:/a/strawberry/strawberry/protobuf/bin/protoc.exe
          #-DProtobuf_LIBRARY_RELEASE=d:/a/strawberry/strawberry/protobuf/lib/libprotobuf.lib


      - name: Run Make
        working-directory: build
        run: cmake --build . --config Release --parallel $(nproc)

      - name: Create directories
        working-directory: build
        run: mkdir gio-modules platforms sqldrivers imageformats styles gstreamer-plugins nsisplugins

      - name: Copy GIO modules
        working-directory: build
        run: copy C:\gstreamer\1.0\msvc_x86_64\lib\gstreamer-1.0\libgiognutls.dll ${GITHUB_WORKSPACE}/build/gio-modules/

      - name: Copy Qt platforms plugins
        working-directory: build
        run: copy d:/a/strawberry/qt/plugins/platforms/qwindows.dll ${GITHUB_WORKSPACE}/build/platforms/

      - name: Copy Qt styles plugins
        working-directory: build
        run: copy d:/a/strawberry/qt//plugins/styles/qwindowsvistastyle.dll ${GITHUB_WORKSPACE}/build/styles/

      - name: Copy Qt SQL drivers plugins
        working-directory: build
        run: copy d:/a/strawberry/qt//plugins/sqldrivers/qsqlite.dll ${GITHUB_WORKSPACE}/build/sqldrivers/

      - name: Copy Qt imageformats plugins
        working-directory: build
        run: copy d:/a/strawberry/qt//plugins/imageformats/*.dll ${GITHUB_WORKSPACE}/build/imageformats/

      - name: Copy gstreamer plugins
        working-directory: build
        run: >
          copy
          C:\gstreamer\1.0\msvc_x86_64\lib\gstreamer-1.0\libgstapp.dll
          C:\gstreamer\1.0\msvc_x86_64\lib\gstreamer-1.0\libgstcoreelements.dll
          C:\gstreamer\1.0\msvc_x86_64\lib\gstreamer-1.0\libgstaudioconvert.dll
          C:\gstreamer\1.0\msvc_x86_64\lib\gstreamer-1.0\libgstaudiofx.dll
          C:\gstreamer\1.0\msvc_x86_64\lib\gstreamer-1.0\libgstaudiomixer.dll
          C:\gstreamer\1.0\msvc_x86_64\lib\gstreamer-1.0\libgstaudioparsers.dll
          C:\gstreamer\1.0\msvc_x86_64\lib\gstreamer-1.0\libgstaudiorate.dll
          C:\gstreamer\1.0\msvc_x86_64\lib\gstreamer-1.0\libgstaudioresample.dll
          C:\gstreamer\1.0\msvc_x86_64\lib\gstreamer-1.0\libgstaudiotestsrc.dll
          C:\gstreamer\1.0\msvc_x86_64\lib\gstreamer-1.0\libgstautodetect.dll
          C:\gstreamer\1.0\msvc_x86_64\lib\gstreamer-1.0\libgstplayback.dll
          C:\gstreamer\1.0\msvc_x86_64\lib\gstreamer-1.0\libgstvolume.dll
          C:\gstreamer\1.0\msvc_x86_64\lib\gstreamer-1.0\libgstspectrum.dll
          C:\gstreamer\1.0\msvc_x86_64\lib\gstreamer-1.0\libgstequalizer.dll
          C:\gstreamer\1.0\msvc_x86_64\lib\gstreamer-1.0\libgstreplaygain.dll
          C:\gstreamer\1.0\msvc_x86_64\lib\gstreamer-1.0\libgsttypefindfunctions.dll
          C:\gstreamer\1.0\msvc_x86_64\lib\gstreamer-1.0\libgstgio.dll
          C:\gstreamer\1.0\msvc_x86_64\lib\gstreamer-1.0\libgstdirectsound.dll
          C:\gstreamer\1.0\msvc_x86_64\lib\gstreamer-1.0\libgstwasapi.dll
          C:\gstreamer\1.0\msvc_x86_64\lib\gstreamer-1.0\libgstpbtypes.dll
          C:\gstreamer\1.0\msvc_x86_64\lib\gstreamer-1.0\libgstapetag.dll
          C:\gstreamer\1.0\msvc_x86_64\lib\gstreamer-1.0\libgsticydemux.dll
          C:\gstreamer\1.0\msvc_x86_64\lib\gstreamer-1.0\libgstid3demux.dll
          C:\gstreamer\1.0\msvc_x86_64\lib\gstreamer-1.0\libgsttaglib.dll
          C:\gstreamer\1.0\msvc_x86_64\lib\gstreamer-1.0\libgsttcp.dll
          C:\gstreamer\1.0\msvc_x86_64\lib\gstreamer-1.0\libgstudp.dll
          C:\gstreamer\1.0\msvc_x86_64\lib\gstreamer-1.0\libgstsoup.dll
          C:\gstreamer\1.0\msvc_x86_64\lib\gstreamer-1.0\libgstcdio.dll
          C:\gstreamer\1.0\msvc_x86_64\lib\gstreamer-1.0\libgstrtp.dll
          C:\gstreamer\1.0\msvc_x86_64\lib\gstreamer-1.0\libgstrtsp.dll
          C:\gstreamer\1.0\msvc_x86_64\lib\gstreamer-1.0\libgstflac.dll
          C:\gstreamer\1.0\msvc_x86_64\lib\gstreamer-1.0\libgstwavparse.dll
          C:\gstreamer\1.0\msvc_x86_64\lib\gstreamer-1.0\libgstwavpack.dll
          C:\gstreamer\1.0\msvc_x86_64\lib\gstreamer-1.0\libgstogg.dll
          C:\gstreamer\1.0\msvc_x86_64\lib\gstreamer-1.0\libgstvorbis.dll
          C:\gstreamer\1.0\msvc_x86_64\lib\gstreamer-1.0\libgstopus.dll
          C:\gstreamer\1.0\msvc_x86_64\lib\gstreamer-1.0\libgstopusparse.dll
          C:\gstreamer\1.0\msvc_x86_64\lib\gstreamer-1.0\libgstspeex.dll
          C:\gstreamer\1.0\msvc_x86_64\lib\gstreamer-1.0\libgstlame.dll
          C:\gstreamer\1.0\msvc_x86_64\lib\gstreamer-1.0\libgstaiff.dll
          C:\gstreamer\1.0\msvc_x86_64\lib\gstreamer-1.0\libgstfaac.dll
          C:\gstreamer\1.0\msvc_x86_64\lib\gstreamer-1.0\libgstfaad.dll
          C:\gstreamer\1.0\msvc_x86_64\lib\gstreamer-1.0\libgstisomp4.dll
          C:\gstreamer\1.0\msvc_x86_64\lib\gstreamer-1.0\libgstasf.dll
          C:\gstreamer\1.0\msvc_x86_64\lib\gstreamer-1.0\libgstasfmux.dll
          C:\gstreamer\1.0\msvc_x86_64\lib\gstreamer-1.0\libgstlibav.dll
          ${GITHUB_WORKSPACE}/build/gstreamer-plugins/

      - name: Copy extra binaries
        working-directory: build
        run: |
          copy d:\a\strawberry\strawberry\sqlite-autoconf-3360000\sqlite3.exe
          copy C:\gstreamer\1.0\msvc_x86_64\bin\gst-launch-1.0.exe
          copy C:\gstreamer\1.0\msvc_x86_64\bin\gst-discoverer-1.0.exe

      - name: Copy dependencies
        working-directory: build
        run: >
          /usr/src/strawberry-mxe/tools/copydlldeps.sh
          -c
          -d .
          -F .
          -F ./platforms
          -F ./styles
          -F ./sqldrivers
          -F ./imageformats
          -F ./gstreamer-plugins
          -R /usr/src/strawberry-mxe/usr/x86_64-w64-mingw32.shared

      - name: Strip binaries
        working-directory: build
        run: find . -type f \( -iname \*.dll -o -iname \*.exe \) -exec /usr/src/strawberry-mxe/usr/bin/x86_64-w64-mingw32.shared-strip {} \;

      - name: Copy nsis files
        working-directory: build
        run: copy ${GITHUB_WORKSPACE}/dist/windows/*.nsi ${GITHUB_WORKSPACE}/dist/windows/*.nsh ${GITHUB_WORKSPACE}/dist/windows/*.ico .

      - name: Copy COPYING license file
        working-directory: build
        run: copy ${GITHUB_WORKSPACE}/COPYING .

      - name: Build Windows installer
        working-directory: build
        run: makensis strawberry.nsi
